ci:
  skip:
    - latexindent
    - poetry-lock
exclude: "^(.cz.yaml)|(poetry.lock)|(requirements.txt)$"
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: "v2.37.0"
    hooks:
      - id: commitizen
  - repo: https://github.com/cmhughes/latexindent.pl
    rev: "V3.19"
    hooks:
      - id: latexindent
        args:
          - "--overwriteIfDifferent"
          - "--silent"
          - "--local"
          - "--yaml=defaultIndent: '  '"
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: "v2.4.0"
    hooks:
      - id: pretty-format-toml
        args:
          - "--autofix"
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v14.0.6"
    hooks:
      - id: clang-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
        stages:
          - commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: "22.10.0"
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.18.4"
    hooks:
      - id: check-dependabot
      - id: check-github-actions
      - id: check-github-workflows
  - repo: https://github.com/python-poetry/poetry
    rev: "1.2.0rc1"
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        files: "^pyproject.toml$"
        args:
          - "--output"
          - "requirements.txt"
          - "--without-hashes"
          - "--without-urls"
