site_name: utility-collection
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: liblaf/utility-collection
      branch: main
  - git-authors
repo_url: https://github.com/liblaf/utility-collection
repo_name: liblaf/utility-collection
edit_uri: edit/main/docs
